name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run format
      - run: npm run build
        env:
          KEY_GH: ${{ secrets.KEY_GH }}
          NODE_ENV: ${{ secrets.NODE_ENV }}
          GA_API_KEY: ${{ secrets.GA_API_KEY }}
          GA_AUTH_DOMAIN: ${{ secrets.GA_AUTH_DOMAIN }}
          GA_DATABASE_URL: ${{ secrets.GA_DATABASE_URL }}
          GA_PROJECT_ID: ${{ secrets.GA_PROJECT_ID }}
          GA_STORAGE_BUCKET: ${{ secrets.GA_STORAGE_BUCKET }}
          GA_MESSAGING_SENDER_ID: ${{ secrets.GA_MESSAGING_ID }}
          GA_APP_ID: ${{ secrets.GA_APP_ID }}
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./public
          cname: victormesquita.dev
